import "./globals.css";
import "./responsive.css";
import Header from "../components/common/header";
import Footer from "../components/common/footer";
import TabFooter from "../components/common/tab-footer";
import MobileFooter from "../components/common/mobile-footer";
import Cursor from "../components/common/cursor";
import MyComponent from '../components/common/smoothscrollgsap-test'
import Loading from '../../src/components/common/loader'
import ContainerWrap from '../../src/components/wrappers/containerWrap'
import BodyWrapper from '../components/wrappers/bodyWrapper'

export const metadata = {
  title: "The Fusion Journey",
  description: "Generated by The Fusion Journey",
};

const RootLayout = ({ children }) => {


  return (
    <html lang="en">
      <BodyWrapper>
        <Cursor />
        <Loading />
        <ContainerWrap>
          <Header />
          <MyComponent>
            <main>{children}</main>
            <Footer />
            <TabFooter />
            <MobileFooter />
          </MyComponent>
        </ContainerWrap>
      </BodyWrapper>
    </html>
  );
}

export default RootLayout;
